### PR TITLE
Added Alternative algorithms for generic recursive functions

### PR DESCRIPTION
**Pull request by aiyer786**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. Include a proper title of the Script that is being entered.

Make sure you have:

- [x] Starred CodeBucket!
- [x] Referred the issue number in the fixes title below.
- [x] Joined our discord server.

Fixes Related Issue(s): #7 

## Type of change

Please delete options that are not relevant.

- [x] New Script
- [x] New Category (Is any new category being made to accommodate this script)

### CODE REVIEW

**Comment by rudrajit1729** [comment]
Please Review and guide him through this @arkch99 . 
@aiyer786 please resolve the merge conflict and see the process for making the PR comment. I have reviewed your code and it goes with the quality standards. Good work on that. Just be accustomed with making PRs.

**Comment by aiyer786** [comment]
Earlier I had added the README files directly on the repos. Now that I have pushed my work and created a pull request, the merge conflict shows the previously added README files. And I am unable to delete that now. Should I create a new pull request after deleting the READMEs or is there another solution?

**Comment by arkch99** [comment]
I'm looking into it.

**Review by arkch99 — APPROVED** [review]

**Comment by arkch99** [comment]
Conflicts resolved and PR merged. Thanks @aiyer786 for contributing!

**Comment by rudrajit1729** [comment]
Try updating on different patches for different PRs to avoid such conflicts @aiyer786 . Thanks for the PR. looking forward to more contributions.

**Comment by aiyer786** [comment]
Thank you @arkch99 for the help! Then I will research about patches first, thank you @rudrajit1729 .

**Pull request merged**
