### PR TITLE
Added Design_And_Graphics_Bucket and a Spirographic Design Script 

### PR DESCRIPTION
**Pull request by souvik199813**
# Description

Added new category - Design_And_Graphics_Bucket and added a spirographic design generation code in python.

Make sure you have:

- [x] Starred CodeBucket!
- [x] Referred the issue number in the fixes title below.
- [x] Joined our discord server.

Fixes Related Issue(s): #27 

## Type of change

Please delete options that are not relevant.

- [x] New Script
- [x] New Category (Is any new category being made to accommodate this script)
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by souvik199813** [comment]
Please Review And Merge. @rudrajit1729 @arkch99 @subhojeet1999

**Comment by souvik199813** [comment]
@arkch99 Please Add a New Issue Related To This Bucket.

**Review by rudrajit1729 — APPROVED** [review]
No Conflict Merge. @arkch99 please add this issue too.

**Comment by arkch99** [comment]
Added issue #27 regarding contributions to the Design_And_Graphics_Bucket.

**Comment by arkch99** [comment]
Merged. Thank you for contributing, @souvik199813 !

**Pull request merged**
