### PR TITLE
add stack structure

### PR DESCRIPTION
**Pull request by kavinkumar999**
# Stack

Stack is a linear data structure which follows a particular order in which the operations are performed. The order may be LIFO(Last In First Out) or FILO(First In Last Out).

Make sure you have:

- [x] Starred CodeBucket!
- [x] Referred the issue number in the fixes title below.
- [x] Joined our discord server.

## Type of change

- [x] Documentation (Updating Documentations)

### CODE REVIEW

**Comment by kavinkumar999** [comment]
please review @rudrajit1729

**Comment by arkch99** [comment]
Most of the programs in your PR have been directly copied from [geeksforgeeks](www.geeksforgeeks.org). Please do not spam again.

**Comment by rudrajit1729** [comment]
@kavinkumar999  Copying and modifying code is alright but direct copy from external website is not allowed. Please refrain from future spamming. Looking forward to quality PRs from you.

**Review by rudrajit1729 — COMMENTED** [review]
Copied

**Comment by kavinkumar999** [comment]
sorry,  I m a beginner , i dont know how to contribute a quality content ? so that's why  i copied the content from the external website

**Comment by kavinkumar999** [comment]
I m a beginner,please suggest some baby steps to contribute @rudrajit1729 @arkch99

**Comment by rudrajit1729** [comment]
@kavinkumar999 this repo is beginner friendly. It's here to kick-start your open source journey. But we don't encourage copied solutions or duplications. Be it a 5 line code or be it 500 lines everything is accepted but shouldn't be directly copied from external websites. Here you can try your take on stack programs rather than direct copy from gfg. To know more about quality PRs please join the discord server. Maintainers are available 24/7 to help you out in this journey. First steps are always the hardest we are with you on this. All Open source contributions are accepted till it has some touch of originality. Refrain from spamming and you too can kick-start your journey in open source.

**Comment by rudrajit1729** [comment]
@kavinkumar999 try looking at other contributions in this repo. You will find a lot of beginner stuff as well as advanced ones. The PRs already merged should give you a brief idea about the contributions. Contribute anything (known algos are accepted as well but don't just copy and paste - that serves no purpose). Think of ways you can better the solutions or can optimize the code structure. There is always room for improvement and maintainers here are always with you in this. I hope this solves your doubts. Looking forward to future contributions.

**Pull request closed without merging**
