### PR TITLE
Updated README with basic introduction for Data Structures CSE_LAB 

### LINKED ISSUE #6: Fix Documentations
There is a constant need of a HERO who can fix documentations. Here is your chance to be the savior. Fix Documentations, elaborate if you can, make the document interesting to read and easy to comprehend. 

Not restricted by any bucket. Wherever there is a need for better documentation, there is a need for your fix.

Restrict from SPAMMING PRs by fixing a minor spell check or making unnecessary edits. Fixing a typo is required but SPAMMING is not.

You don't need to be assigned to fix README files, if you can better it we welcome your PR.

### PR DESCRIPTION
**Pull request by aiyer786**
# Description

Updated README for Data structures in CSE_Lab_Bucket.

Make sure you have:

- [x] Starred CodeBucket!
- [x] Referred the issue number in the fixes title below.
- [x] Joined our discord server.

Fixes #6 

## Type of change

Please delete options that are not relevant.
- [x] Documentation (Updating Documentations)

### CODE REVIEW

**Comment by rudrajit1729** [comment]
@aiyer786 I have updated your comment here. Please make sure to make future PRs following the format.

**Comment by rudrajit1729** [comment]
@aiyer786 please check your README files for spell checks. Also the Commit comment should be of the format "Updated README" . Also the PR template attached in this PR has been modified. Please take a look and generate future PRs in this format. 
Looking forward to your changes before it can be merged.

**Comment by aiyer786** [comment]
@rudrajit1729  I did a spell check and made the required changes. I am not able to commit those changes, it is generating an error while running a check on it. The error is generated by Labeler/ label. I have copied the description you have provided and also the commit message.  However that is not fixing the error here. Please guide me through this.

**Comment by rudrajit1729** [comment]
@aiyer786 please check whether the files you changed are showing under your forked repository. You can find your forked repo in your profile repository tab. Check there and update readme in your forked repo. Currently your forked repo has no changes.

Attached Link : https://github.com/aiyer786/CodeBucket/blob/master/CSE_Lab_Bucket/Data%20Structures/README.md
Check here the files have not been changed yet. Update it here and generate a PR.

**Comment by rudrajit1729** [comment]
@aiyer786 after having a check I noticed you have changes made in your dev branch(patch-1). Fine with me but be sure to reflect those changes in your master branch as well. Also the labeler issue has been fixed now, it shouldn't cause trouble.

**Comment by rudrajit1729** [comment]
Thanks for the PR. We appreciate the baby steps and I look forward to quality PRs from you. Thanks.

**Comment by aiyer786** [comment]
Thank you for merging. Sorry for all the trouble you had to go through, I am still struggling to get comfortable with GitHub. Thanks to your guidance up till now, I made some progress!

**Comment by aiyer786** [comment]
Also, I wanted to write other READMEs in a similar format if you allow me to!

**Review by rudrajit1729 — COMMENTED** [review]
hacktoberfest-accepted

**Comment by rudrajit1729** [comment]
Sure @aiyer786 . Adding README files are always welcomed. Submit PR after adding necessary README files under a single PR.
Also you can go ahead with implementing the algorithms you requested to be assigned for.

**Pull request merged**
