### PR TITLE
Added Basic GUI Calculator

### PR DESCRIPTION
**Pull request by souvik199813**
# Description
Added Basic GUI Calculator

Make sure you have:

- [ ] Starred CodeBucket!
- [ ] Referred the issue number in the fixes title below.
- [ ] Joined our discord server.

Fixes Related Issue(s): #3
## Type of Changes
Added Basic GUI Calculator

Please delete options that are not relevant.

- [ ] New Script
- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by souvik199813** [comment]
Added Basic GUI Calculator. Thanks. @subhojeet1999

**Review by subhojeet1999 — CHANGES_REQUESTED** [review]
Calculator not working properly please correct.

**Review by rudrajit1729 — CHANGES_REQUESTED** [review]
Calculator doesn't work properly. Please Update. Also add a detailed readme on how to set up the project in local system.

**Review by rudrajit1729 — COMMENTED** [review]
This doesn't fulfill criteria for WebBucket as this is a Desktop GUI. Please find the right bucket. Need to close this PR.

**Pull request closed without merging**
