### PR TITLE
Added HackerRank Java OOPs

### LINKED ISSUE #12: Add CP Platform Scripts
Add competitive programming platform practice/contest questions.

Please refrain from uploading scripts of ongoing contests.

Accepted platforms: Hackerrank, Codechef, Codeforces, Leetcode, Algoexpert.

### PR DESCRIPTION
**Pull request by AbhijitDutta338**
# Description

Added HackerRank Java OOPs

Make sure you have:

- [x] Starred CodeBucket!
- [x] Referred the issue number in the fixes title below.
- [x] Joined our discord server.

Fixes Related Issue(s): #12  

## Type of change

Please delete options that are not relevant.

- [x] New Script
- [x] New Category (Is any new category being made to accommodate this script)

### CODE REVIEW

**Comment by AbhijitDutta338** [comment]
Please review and merge @rudrajit1729 @arkch99

**Comment by rudrajit1729** [comment]
Can you add a readme file linking the problem statements which has been solved. @AbhijitDutta338

**Comment by AbhijitDutta338** [comment]
Added Readme file and renamed CP_Bucket to CP_Platform_Bucket. Please review @rudrajit1729 @arkch99 .

**Comment by rudrajit1729** [comment]
Thanks for the PR. @AbhijitDutta338

**Review by rudrajit1729 — COMMENTED** [review]
hacktoberfest-accepted

**Pull request merged**
