### PR TITLE
Stone Paper scissors game in Web Bucket

### PR DESCRIPTION
**Pull request by subhankarghosh2000**
# Description

Stone Paper scissors game in Web Bucket

Make sure you have:

- [x] Starred CodeBucket!
- [x] Referred the issue number in the fixes title below.
- [x] Joined our discord server.

Fixes Related Issue(s): #2 #3

## Type of change

Please delete options that are not relevant.

- [x] New Script
- [x] New Category (Is any new category being made to accommodate this script)

### CODE REVIEW

**Comment by subhankarghosh2000** [comment]
Check @arkch99 @debargha-10 @rudrajit1729

**Comment by rudrajit1729** [comment]
Add the same thing in Game Bucket as well before we merge this @subhankarghosh2000

**Review by rudrajit1729 — CHANGES_REQUESTED** [review]
Add The Game in Game Bucket as well

**Comment by subhankarghosh2000** [comment]
Check @arkch99 @debargha-10 @rudrajit1729

**Review by rudrajit1729 — APPROVED** [review]

**Comment by arkch99** [comment]
Thanks @subhankarghosh2000 for contributing!

**Pull request merged**
